global:
  bindAddr: ":9092"
  buffersize: 100

# logger settings
log:
  format: "text"
  level: "debug"

# action plugin settings
action_plugins:
  - name: "ht-aws-asg-action-plugin"
    address: "localhost:8888"
    type: "grpc"

  - name: "fn-k8s-drainer"
    address: "localhost:8889"
    type: "fn"
    properties:
      app: "ht"
      function: "drain"

# action plugin rules
rules:
  - name: "spot_rebalance"
    description: "price alert to asg rebalance"
    event_type: "prometheus.server.alert.SpotInstanceTooExpensive"
    action_plugins:
      - "ht-aws-asg-action-plugin"
    match:
      - asg_name: "marci-test"

  - name: "spot_to_fn_drainer"
    description: "spot to FN k8s drainer"
    event_type: "prometheus.server.alert.SpotTerminationNotice"
    action_plugins:
      - "fn-k8s-drainer"
    match:
      - cluster_name: "marton-cluster"
